AllCops:
  TargetRubyVersion: 2.6
  NewCops: enable
  SuggestExtensions: false
  Exclude: 
    - "lib/miti/date_data.rb"

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Layout/LineLength:
  Max: 120

Metrics/BlockLength:
  Max: 120
  Exclude: 
   - "miti.gemspec"
   - "spec/**/*"
   - "lib/miti/data/date_data.rb"

Metrics/MethodLength:
  Max: 9
  Exclude:
    - "lib/miti/data/date_data.rb"

Metrics/ClassLength:
  Max: 100
  Exclude:
    - "lib/miti/data/date_data.rb"
